version: '3'


services:
  nginx:
    image: nginx:1.15
    restart: always
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./dhparam:/etc/ngnix/dhparam
      - ./certbot/conf:/etc/ngnix/ssl
      - ./certbot/data:/usr/share/ngnix/html/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.create_app:create_app()"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - flask-app
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/ngnix/html/letsencrypt --email deniss.hohlov@gmail.com --agree-tos --no-eff-email -d t10.ee
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/usr/share/ngnix/html/letsencrypt
networks:
  my-network: