version: '3'


services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network
    depends_on:
      - flask
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.create_app:create_app()"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
            - flask-app
networks:
  my-network: